### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by ragingdave**
fix issue with volume mapping

### CODE REVIEW

**Comment by haugene** [comment]
LGTM

**Comment by timhaak** [comment]
Cool just transferred the equivalent of 60 pounds (R1,234). 

Which should cover the two months that have gone through already and this month. 

:)

Tim Haak
+27 83 778 7100
tim@haak.co <mailto:tim@haak.co>

**Comment by haugene** [comment]
Was that meant to go here @timhaak ? :)

**Comment by timhaak** [comment]
Not at all :)

**Pull request merged**
